[package]
name = "reducer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sqlsync-reducer = "0.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.105"
log = "0.4.20"
futures = "0.3.28"